<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    /*new Promise((resolve, reject) => {
        setTimeout(()=>{
            resolve("这是1秒后");
        },1000)
    }).then((data) =>{
        console.log(data);

        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve();
            },1000)
        })

    }).then(() => {
        console.log("这是两秒后");

        return new Promise((resolve, reject) => {
            setTimeout(() => {
                reject("三秒后的catch error");
            },1000)
        })
    }).then(() => {
        console.log("这是三秒后");
    }).catch(err => {
        console.log(err);
    })*/

    /*new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve("这是1秒后");
        }, 1000)
    }).then((data) => {
        console.log(data);
        return Promise.resolve();

    }).then(() => {
        console.log("这是两秒后");
        return Promise.resolve("三秒后的catch error");

    }).then(err => {
        console.log(err);
    })*/


    /*new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve("这是1秒后");
        }, 1000)
    }).then((data) => {
        console.log(data);
        return "第二次";

    }).then((data) => {
        console.log(data);
        return "第三次";

    }).then(data => {
        console.log(data);
    })*/

    new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve("这是1秒后");
        }, 1000)
    }).then((data) => {
        console.log(data);
        //throw "第二次错误";
        return "第二次";

    }).then((data) => {
        console.log(data);
        throw "第三次错误";

    }).then(data => {
        console.log(data);
    }).catch(err => {
        console.log(err);
    })

</script>
</body>
</html>